### ISSUE TITLE
Thick bundle representation to allow for deduplication of layers

### ISSUE THREAD

**Issue by glyn** [deislabs/cnab-spec#129]
The spec's [file format for thick bundles](https://github.com/deislabs/cnab-spec/blob/c9050a38ac03d55c766fa6e42abba389816c2b38/104-bundle-formats.md#file-format-for-thick-bundles) recommends (through the use of "SHOULD") one tar file per image in which case layers common to more than one image will be duplicated. To facilitate more  space-efficient representations which deduplicate layers, this should be weakened to "MAY". This also avoid bias towards Docker and OCI image types; it is not clear what representation should be used for future image types.

An alternative, space-efficient format such as [OCI image layout](https://github.com/opencontainers/image-spec/blob/master/image-layout.md) should also be listed as an option (another "MAY").

**Comment by technosophos** [comment]
It would be hard to write an implementation based on the specification in this case. And it would be hard to share CNAB bundles in this case, as well, since we have no prescription for what is inside of the image.

If we were to change the proposal in this way, we'd need to define both a layered export and a non-layered export. Otherwise there's no point at all in defining an export format whose contents are indeterminate.

**Comment by technosophos** [comment]
I spoke too soon! I just saw 130! That is a good idea!
