### ISSUE TITLE
Inconsistent Formatting Question

### ISSUE THREAD

**Issue by astrieanna** [deislabs/cnab-spec#210]
There is some formatting that seems to be used inconsistently across files in the repo.

* ["thick" bundles](https://github.com/deislabs/cnab-spec/blame/master/101-bundle-json.md#L33) vs [thick bundles](https://github.com/deislabs/cnab-spec/blame/master/100-CNAB.md#L35) vs [Thick Bundles](https://github.com/deislabs/cnab-spec/blame/master/805-airgap.md#L43)
  Most places (files 100, 103, 300) use thick bundles; 101 uses quotes sometimes; 805 capitalizes.

* What does it mean when a term is italicized?
  * In 100, terms are italicized and defined on first mention
  * In 101, [thin bundle](https://github.com/deislabs/cnab-spec/blame/master/101-bundle-json.md#L31) is italicized on first mention. Later, [thin](https://github.com/deislabs/cnab-spec/blame/master/101-bundle-json.md#L35) and [thick](https://github.com/deislabs/cnab-spec/blame/master/101-bundle-json.md#L323) each get italicized once in the file -- maybe for emphasis.
  * In 102, [run tool](https://github.com/deislabs/cnab-spec/blame/master/102-invocation-image.md#L20) is italicized and defined on first mention. Later, the phrase [MUST be an executable file](https://github.com/deislabs/cnab-spec/blame/master/102-invocation-image.md#L69) is italicized -- maybe for emphasis.
  * In 103, in [Environment Variables](https://github.com/deislabs/cnab-spec/blob/master/103-bundle-runtime.md#environment-variables), `installation name`, `bundle name`, and `action` are italicized because they are the terms being defined and used to describe the proper values for env variables. Through out the file, other phrases are italicized, probably for emphasis.
  * In 104, [thin and thick bundle](https://github.com/deislabs/cnab-spec/blame/master/104-bundle-formats.md#L14) are italicized and defined again. [All](https://github.com/deislabs/cnab-spec/blame/master/104-bundle-formats.md#L40-L41) is italicized for emphasis twice.

The italicized-for-maybe-emphasis phrases do not consistently seem to be of more importance than the rest of the document. In a spec, where there are many MUST sentences, I'm not sure that italicizing phrases for emphasis makes sense.

It is also bit confusing to italicize thick and thin bundle the first time time it appears in a file, despite the definition appearing in full in 100-CNAB. If the spec is intended to be read from the beginning and italics are intended to be used for the first occurrence of new terms, then a term should probably only be italicized the first time it appears in the spec document as a whole (rather than an individual file).

cc @ryanmoran

**Comment by technosophos** [comment]
First occurrence of an important technical term in the spec should be in italics: _thin bundles_, and should be followed by a definition. Later occurrences do not need to be in italics. The "scare quotes" should only be used to reference an outside jargon used against the definition of the spec ('Some people term JavaScript developers with database experience "full stack developers"'). So thick/thin bundles should never be in quotes like that.

Italics may be used (sparingly) for emphasis: "While in most cases the parameter should be included, with _thin_ bundles, you may..."

My guess is that the inconsistencies made their way in due to a combination of lots and lots of rewrites/reorgs and copying styles used elsewhere.

**Comment by jlegrone** [comment]
Also "CNAB bundle" vs. "bundle" or "CNAB"
