### ISSUE TITLE
Update schema to be consistent with limitations of canonical json

### ISSUE THREAD

**Issue by carolynvs** [deislabs/cnab-spec#256]
Canonical JSON doesn't allow for decimal numbers, only integer. We should update the `$schema` we use to a customized json schema draft 7, switching from numbers to integers for fields such as `minimum` etc.

For example, draft 7 has maximum defined as

```json
"maximum": {
  "type": "number"
},
```

but a value of `0.5` isn't valid, so we would copy draft 7 and change maximum to 

```json
"maximum": {
  "type": "integer"
},
```

Here is the related issue that prompted me to open this: https://github.com/deislabs/cnab-go/issues/115

**Comment by glyn** [comment]
According to https://github.com/mozilla/normandy/issues/1210#issue-306614862, some canonical JSON implementations do appear to support decimal numbers, but are not consistent with each other, thus defeating the object somewhat. Also, there is an assertion there that there is no standard for canonical JSON, so it's probably best not to go _off piste_ and come up with our own implementation that includes decimals otherwise we'll risk not interchanging with anyone else.

**Comment by radu-matei** [comment]
Not sure about changing the `number` types to `integer` though. 

That being said, I don't see any scenario where we would stop using canonical JSON - currently it is the only way to ensure that the same contents of a bundle would yield the same content digest, which is an important part of the security specification.

**Comment by glyn** [comment]
I think someone, possibly @carolynvs, was thinking of using strings when decimals really are needed. I'd like to see all the usages of `maximum` to know whether any of them need to be decimals.
