### ISSUE TITLE
101-bundle-json.md questions/comments

### ISSUE THREAD

**Issue by duglin** [deislabs/cnab-spec#39]
It feels a little like the bundle definition is repeated 3 times, first informally (in the section that starts with "A bundle.json is broken down into the following categories of information...") because it talks about it in generic terms - but also tries to be kind of prescriptive about its contents and only partially using RFC2119 keywords so I'm not sure how "spec-ish" this section is meant to be, then we see an example (which comes across as defining a spec by example), and finally again with a more formal definition (with the full RFC2119 keyword usage). I think it would read better if you either 1) put the RFC2119 section first and then showed a concrete example, or 2) showed the example with perhaps a short paragraph providing an overview (but not as prescriptive as it is today), and then got more formal with the RFC keyword section. I prefer 1)

> And here is how a "thick" bundle looks...

Where does the actually image itself live? I kind of expected to see either a property in the json with the binary data of the image, or some mention of where the binary image resides on disk, in a tar file, etc...

The 'thick' bundle has a "platform" section with os and arch. I would have expected to see that being needed on the thin side too, or if not, then is this duplicating info that's part of the binary image itself? It seems it would be better to avoid the duplication and have the bundle processor get it directly from the image since it's error prone to duplicate it and can be complex, like in the case of a multi-arch image.

> Fields that do not match this specification SHOULD cause failures

s/SHOULD/MUST/ otherwise the MUSTs above it aren't really MUSTs. And it should say how those failure manifest themselves - e.g. stop processing of the bundle?

> Informational Metadata

This section should be more clear on the type of this metadata - e.g. "keywords" - is it a single string with comma separated words? an array of strings/words?

> The appropriate invocation image is selected using the current driver.

The term "current driver" hasn't  been used before (or I missed it), so I'm not sure what it means.

> The bundle.json maps image metadata (name, origin, tag) to placeholders within the bundle.

Where are name, origin and tag defined?

Certain fields are required (e.g. version and image.description), but its not clear to me why - at least not yet. Are these required for a bundle processor to do its job? I'm guessing no, and if not I wouldn't make them required - it become noise/busywork for the author - and just asks them to fill it in with random (meaningless) garbage. This about the bare minimum a bundle needs to work, and only those things should be REQUIRED. You can make the other ones RECOMMENDED or SHOULDs.

> Field Selectors

It's not clear to me what this section is for.

> Parameters

I can't decide how I feel about this section. On the one hand I agree there will be a need to parameterize things, however, where does the normal install tool fit into this? For example, are you planning on this replacing Helm's templating stuff? Or to leverage it? 

> Credentials

How do you envision these being setup at runtime? By whom?

**Comment by ryanmoran** [comment]
Hey @squillace,

After spending a bit of time reading through the spec and then through some issues, I still cannot find a reasoning for the separation of parameters and credentials. Your comment above was the closest to stating a reason.

> As credentialsets are likely to be handled very differently than simple "parameters", they are made separate to keep runtime separation of concerns.

It seems like separating them will likely lead to a duplication of the specification of inputs across general `parameters` and the special-case of `credentials`.

For example, we already see duplication in the portions of the parameters and credentials section that describe destination. Unfortunately, while those areas seem like duplication on first-pass, there are subtle differences between those overlapping concerns that could lead to confusion for bundle authors.

Can you dig into why these are fully separated concerns?

**Comment by technosophos** [comment]
The reason is that `parameters` are semantically different than `credentials`.  Parameters are for passing configuration to the application. Credentials are for asserting the identity and permissions of the agent performing the action.

A credential is a kind of parameter that is earmarked (by the bundle creator) as needing special treatment for security reasons. Typically, it is intended to contain the credentials necessary for the use of the bundle, and the values are intended to be _the credentials of the agent performing the installation_. In other words, there is an _identity relationship_ between the agent doing the installation and the credentials supplied. (This is not true of paramters)

The spec makes recommendations about what a _runtime_ should do with credentials (as opposed to parameters) when it comes to storage and retention of these. And it also recommends that credentials not be stored. While I wrote the spec to be fairly lenient, it is my _opinion_ that credentials should not be stored, while parameters should. Because semantically, they tell different stories. A parameters is a _piece of configuration that should be visible and persist_, while a credential is a _piece of identity (authn/z) that should _vary depending on who is performing an action_. To treat parameters and credentials as the same would be to treat the port number of a web service as the same category of data as the password of the person who started that web server.

Finally, there is an interest in being able to audit what permissions a bundle requires in order to be installed. While we could not find a general purpose mechanism that would describe the AuthZ layer, we could pretty easily describe the general AuthN layer(what are the keys, certs, passwords, tokens, etc?). We opted to take that approach for the first cut of the spec.

So in my mind, there is a clear conceptual difference between a parameter (configuration for the app) and a credential (identity for the agent) that not only _can_ be separated, but _must_ be separated in order for us to make stronger security assertions about the bundle. For that reason, I don't look at duplication of a few field names as a sufficient reason for changing the design.

Hope that clarifies things for you.

**Comment by ryanmoran** [comment]
That context does help as it was unclear to me from the spec that a credential has an intended audience of the agent performing the installation within the invocation image. The security concern is reasonable.

To make my understanding clearer, I'd like to propose a scenario and ask how you would approach apportioning the inputs to the bundle as either parameters or credentials.

In this example I have 2 processes that communicate at runtime:
- a 12-factor application
- a database

Both are packaged together in a single bundle and the operator provides inputs to configure the bundle during installation.

These processes communicate over a public network and in order to secure their communication that connection is encrypted with mutual TLS and requires username/password authentication.

Deploying these process requires some other configuration. I need to know where to deploy each process and a username/password to use when using my deployment tool.

I can imagine that to bundle these processes using CNAB I would need inputs for the following:
- `app-deployment-target` (the location to deploy the 12-factor app)
- `db-deployment-target` (the location to deploy the database)
- `deployer-username` (the username to use when deploying either the app or the database)
- `deployer-password` (the password to use when deploying either the app or the database)
- `database-ca-certificate` (the CA that can be used to verify the certificate presented by the db)
- `database-certificate` (the certificate presented by the db for TLS connections)
- `database-private-key` (the private key used by the db to encrypt TLS communication)
- `app-ca-certificate` (the CA that can be used to verify the certificate presented by the db)
- `app-certificate` (the certificate presented by the app for TLS connections)
- `app-private-key` (the private key used by the app to encrypt TLS communication)
- `database-username` (the username the app uses to authenticate with the db)
- `database-password` (the password the app users to authenticate with the db)

There are inputs in this list that I would classify as secrets. From your description though, it is still unclear to me if they would be `credentials` or `parameters` as described within the spec. Some of these strike me as secrets belonging to my distributed system and others are secrets of the deployment mechanism upon which my distributed system runs. Can you help me to understand which inputs belong where and how you see that aligning with the security implications you have stated above?

**Comment by technosophos** [comment]
Remember that the parameters and credentials are for the _invocation image_. So you would be able to store many of those things inside of a vault system (or generate them, etc) and not have to pass them all in as parameters or credentials. Or generate certificates on the fly, etc. You don't necessarily need to provide a 1:1 mapping. The Porter demos show some of these techniques, as to a number of the example bundles in the github.com/deislabs/bundles repo.

The spec doesn't necessarily say how parameter storage must be implemented (that seems overreaching). But if it is stored securely, there's no real reason why you wouldn't be able to put all but `deployer-username` and `deployer-password` inside of parameters. After all, they are properly parameters for the application. 

But if the release info (i.e. the claim) is not stored in a trustworthy place, yet credentials are, I suppose you could treat them as credentials. It will just make managing the application harder, since those pieces of data would have to be supplied for every relevant operation.

/cc @jeremyrickard

**Comment by ryanmoran** [comment]
Hey @technosophos, thank you for this further explanation.

After reading the spec [section on credentials](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#credentials) again, I still cannot see how I would have fully understood that without the context you have given above.

If the intention is to continue to separate `credentials` and `parameters` as differing concerns within the spec, I think it is worth spending some time to better articulate some of what you have said above.

For example, I think it is worth being very explicit that the `credentials` field is for _those credentials used by the agent performing the installation_. Maybe you would go so far as to rename the field to `installation_agent_credentials`.

Additionally, it is worth stating that the `parameters` field is for storing configuration inputs for the application. With that in mind, it is worth specifying that there may be parameters that are sensitive in nature, fields that you might even describe as credentials, that would still be included in the `parameters` field because they logically "belong" to the application and not the installation agent.

I think with the addition of these two pieces of context, the spec makes considerably more sense, even if I am still unsure that I agree that this type of separation is warranted.

**Comment by technosophos** [comment]
Alright. I will try to improve that section.

**Comment by squillace** [comment]
I'll help out here even more.

**Comment by technosophos** [comment]
I'm unclear as to what work remains on this issue. I think that all of the original issues have been resolved, and I believe we have clarified the credentials section. Is there anything else in here we need to track?

**Comment by squillace** [comment]
I think, ultimately, this issue was addressed by the modifications that @technosophos made in #106. The precise difference between the two seems unrelated to the conversation in #114, which is about STDIN as a passing mechanism option. @ryanmoran can I close this issue?

**Comment by ryanmoran** [comment]
Yes. I feel all of my questions were answered.

**Comment by glyn** [comment]
Closing. If we missed something, please re-open.
