### ISSUE TITLE
200 Repositories, why not OCI distribution

### ISSUE THREAD

**Issue by philips** [deislabs/cnab-spec#51]
Why is [200 repositories](https://github.com/deislabs/cnab-spec/blob/master/200-repositories.md) not based on the [OCI distribution spec](https://github.com/opencontainers/distribution-spec)? 

OCI distribution was designed to handle different mime-types and since CNAB is a single bundled string of bytes this seems like a reasonable use case for it.

The upside is that every OCI/Docker registry could trivially add CNAB support without a ton of code changes.

**Comment by bacongobbler** [comment]
Hey @philips, we are actively discussing this with the Docker team over in https://github.com/deislabs/duffle/issues/300. The repository spec as it stands is still in-flux. We'd love to hear your feedback!

**Comment by technosophos** [comment]
The repository spec is very early, and is :100: going to change (probably substantially) over the coming months.

**Comment by jbeda** [comment]
It would be great to see support for uploading/downloading file bundles (with layers/dependencies) be separated out from the rest of the CNAB spec.  There are use cases for having a "signed tarball" system outside of application packaging.  This could either be by using/evolving the OCI dist spec or working widely to motivate something new.  Clean layering here will make it more likely that the spec will be more widely used.

**Comment by bacongobbler** [comment]
Hey @josephschorr,

During very early proof-of-concept stages, We tried to fork distribution and add custom media types for CNAB, but due to time constraints/lack of experience when it comes to adding custom media types to docker/distribution we decided to go with a quick MVP to demonstrate the idea of hosting bundles in a repository. We do think that moving to the OCI distribution spec would be a great idea for the spec.

I think it bears repeating that the repository spec is *very* early and will be subject to change over the coming months.

**Comment by philips** [comment]
@bacongobbler @technosophos I would love to figure out how to get a commitment from the team that the goal is to use OCI distribution as the only network transport.

The cloud native ecosystem really doesn't need yet another binary asset server that everyone has to implement, audit, and maintain.

I am sure any number of folks at Docker or working on the open containers project would help. cc @caniszczyk

**Comment by SteveLasker** [comment]
Not a surprise, but yes. We have been working to get all the right folks together to have CNAB _and Helm_ take advantage of all the work done in Registries. This [Proposal to converge helm repositories with docker registries #55](https://github.com/helm/community/pull/55) has become a lengthy discussion on the topic. Short answer; any company that has invested in making registries scale would really like to take advantage of that work, rather than create yet another.

**Comment by mattfarina** [comment]
@philips There have been background conversations going on about just this. We have now taken the conversation to the OCI to figure out the appropriate way to move this forward.

**Comment by garethr** [comment]
@philips yes, we've been having the same conversations. Docker App (https://github.com/docker/app
) implements CNAB and pushes to an OCI registry all ready. Thinks moving a touch quickly the last few weeks. 

@simonferquel has been doing some of this work, likely to have more links and information.

**Comment by wking** [comment]
[Here][1] is the `dev@opencontainers.org` thread on distributing arbitrary media types in [distribution-spec][2] registries, for folks who want to follow along there ;).

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/U49AZRFo3tk
[2]: https://github.com/opencontainers/distribution-spec
