### ISSUE TITLE
Lean on JSON Schema for parameter validation?

### ISSUE THREAD

**Issue by wking** [deislabs/cnab-spec#54]
The spec has had parameter validation since fd3d65a0ffe (#1), but the existing constraints are fairly limited and are maybe unique to this specification.  Can we use JSON Schema's [validation keywords][1] (or a subset of those keywords) instead of rolling a custom validation format?

[1]: https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6

**Comment by technosophos** [comment]
FWIW, it was not a custom validation format. It was ARM Template syntax, which was the base syntax from which CNAB originally derived. ARM, for example, did not use floats because of the precision problems. ARM was also oriented around generating formats easy for UIs to display. But really, this is the last vestige of ARM, so... I am fine with removing it.
