### ISSUE TITLE
Confusion between image names and digests

### ISSUE THREAD

**Issue by simonferquel** [deislabs/cnab-spec#61]
`images` and `invocation images` objects have both an image reference and a digest field. However, an image reference can already contains a digest (for immutable image references), which is very confusing.

I suggest that we drop the `digest` field, and make a comment on the `image` field like:
- `image` MAY contain a muttable image reference (`[registry/]repository[:tag]`) when the package is under development
- `image` MUST contain a digested (immutable) reference (`[registry/]repository[:tag]@<digest>`) when the package is distributed (as a signed thin or thick CNAB, or trough an OCI registry).

**Comment by technosophos** [comment]
This was originally an artifact of the confusion between image IDs and the SHA computed by the registry. @jeremyrickard do we have enough clarity on this to choose one over the other at this point?

**Comment by jeremyrickard** [comment]
I think we have enough clarity to know that the _proper_ thing for a signed bundle is a digested (immutable) reference.

I like Simon's suggestion and I think the mutable image reference during development is good from a UX perspective. We need to tweak what Duffle is doing to support this (i.e. we are signing the bundles w/o digesting the image right now).

**Comment by technosophos** [comment]
Just to be 💯 clear, I should drop the `digest` field out of the spec at this point, and instead recommend that the `@sha...` be added to the image.

**Comment by glyn** [comment]
A digest field seems useful for image types that don't embed a digest in an image name.

The digest field also simplifies checking that all images in a signed bundle have digests. Without a digest field, the check would need to parse both standard and custom image name formats to check for the presence of a digest.

How painful would it be to retain the digest field and potentially duplicate the digest information for some image types like docker?

**Comment by technosophos** [comment]
VM images are definitely a case where adding the SHA into the name is... not the norm at all. Also, since `@` is a legal naming character in some file systems, I guess it could artificially constrain image names (or misinterpret image names) for VM images.

That said, it is sort of ambiguous to have two digests (one in the name, and one in the `digest` field). What does a _runtime_ do when it is given a bundle with two different SHAs?

**Comment by glyn** [comment]
> That said, it is sort of ambiguous to have two digests (one in the name, and one in the `digest` field). What does a _runtime_ do when it is given a bundle with two different SHAs?

Fail to install the bundle and produce an error saying why. This _should_ be an edge case, of course.

**Comment by simonferquel** [comment]
Maybe make the image field either a registry ref or a structure url+digest? The type of field would depend on the image type value.

**Comment by technosophos** [comment]
With the exsiting `type`/`name`/`digest` fields, I think we have what we need. I think @glyn may be right -- it may be better to leave `digest` for use by other things, and just double up on the SHA for OCI-style images.

**Comment by technosophos** [comment]
After a long period of debate, it appears that the consensus on this is that we will _leave_ the `digest` field because it is necessary for non-Docker images (like VM images). I'm closing my associated pull request. I'll leave this issue open for a little while longer in case people still want to weigh in with additional arguments.

**Comment by technosophos** [comment]
I believe this is now closed.
