### ISSUE TITLE
Timestamp suggestion

### ISSUE THREAD

**Issue by amanjeev** [deislabs/cnab-spec#63]
Starting a discussion about the question/TODO on [104-claims](https://github.com/deislabs/cnab-spec/blob/a51d5b11700b076625bedb9ac08dfa73481adfc6/104-claims.md) -

> TODO: What is the best timestamp format to use? Does JSON have a preference?

I know you might have thought about it already but I could not find a Github issue with this so just thinking out loud -- How about using **ISO-8601** formatted timestamp?

**Comment by technosophos** [comment]
I went to hunt this down, since it is not specified in the JSON spec. It looks like the ECMAScript standard (JavaScript) defines it this way: https://www.ecma-international.org/ecma-262/9.0/index.html#sec-date-time-string-format

That is ISO-8601 Extended Format. So I will adopt @amanjeev 's recommendation and add that to the spec.
