### ISSUE TITLE
Dependency Management Model for bundles

### ISSUE THREAD

**Issue by nadundesilva** [deislabs/cnab-spec#65]
I've been going through the Spec and I was thinking about how a user can create a bundle that depends on multiple bundles. In the current Spec, we do have the ability to share bundles and thereby reuse them. But there is no concept of dependencies between them.

In a distributed system composed of many components running on heterogeneous environments, we would probably create multiple bundles for different components and deploy them. If I am to use a bundle that depends on other bundles, I need to separately pull each bundle and then install them separately.

However, when the number dependencies gets larger, finding all the dependencies and manually pulling them would be really hard for a user.

Do we have any plans to address this issue through the Spec?

In my opinion, we would have to introduce a Dependency Management Model for the bundles. By embedding this into the Spec at an early stage we can make sure that the bundles can be scaled well into larger distributed systems with many components.

Unfortunately, I do not have an exact proposal for this as of now. However, in my opinion we would have to consider the following if we are going to introduce this. (I am willing to contribute, if this seems like something you would like to add to the Spec)

1. Specifying the dependencies in the bundle.json file
2. Specifying how the dependencies would be shared (we can probably adjust the repository section in the Spec to support this.)
3. Specify how pulling from the repository should resolve the dependencies and install them.
4. What should be the policy when multiple bundles require the same bundle as a dependency

WDYT?

**Comment by nadundesilva** [comment]
After taking a look at [Porter](https://github.com/deislabs/porter), it looks like you have already planned to introduce a Dependency Model for CNAB. Do you have any plans to add it to the Spec as well?

**Comment by carolynvs** [comment]
Porter works around the lack of dependencies in the runtime spec by identifying dependencies before the invocation image is built, and then including them in the invocation image at build time. The final result is a single invocation image and the tool executing the bundle (duffle) is unaware that dependencies were involved at all.

**Comment by garethr** [comment]
This is similar to the view we came to thinking about this in docker app as well. That dependencies are more of a build-time concern in CNAB. I'll try and rationalise that view.

> In a distributed system composed of many components running on heterogeneous environments, we would probably create multiple bundles for different components and deploy them.

I think this is definitely true. If we take a whole system view that's not one application, but multiple. That doesn't say anything about dependencies however.

> I need to separately pull each bundle and then install them separately.

Thinking about this first in the context of these not being dependent, this is a common need in other packaging ecosystems too. One popular approach is the `*File`. `GemFile`, `PipFile`, `PuppetFile`, `HelmFile`, etc. This isn't something for the spec, but I'd love to see a `CNABFile` tool created.

> If I am to use a bundle that depends on other bundles

I think it would be good to describe some specific examples here to test out whether this is needed at runtime. I think this is partly about the scope of what you package, which is probably something of a personal choice. I think it's useful to remember that CNAB is also a way of packaging other types packages. So for example I'd (personally) not expect to build a MySQL CNAB, or an Redis CNAB and a Go web app CNAB and have dependencies between them. I'd expect that to be one CNAB. I think concrete examples would test out whether this is a runtime concern.

If it is it then adding dependencies into the Bundle spec would make sense. I would caution that it's a non-trivial problem to specify well, with lots of gotchas. For instance specifying how parameters and credentials work in the dependency graph. I'd probably advocate for keeping that outside the scope of 1.0, but that doesn't mean not starting the conversations and taking a run at a proposal.

**Comment by youreddy** [comment]
Hey @garethr, here's an example I was thinking about: 

Say an operator wanted to deploy Istio via helm on a Kubernetes cluster using CNAB bundles and I had the following available to me: 

A bundle for provisioning the cluster
A bundle for installing helm and checking that it's correctly deployed
A bundle for installing Istio via helm

Each bundle would need to specify the credentials and parameters it's dependent on to perform its job. For example, the helm bundle would need Kubernetes credentials and knowledge of where the cluster is located. Same for the Istio bundle.

As it is today, the operator would need to sequentially install each bundle and then go back to configure the parameters and credentials for each dependent bundle. I could imagine that being a time consuming and error prone process.

There are cases where the operator could set the credentials and parameters ahead of installing the dependent bundles. However, that isn't always possible. For example, when provisioning Kubernetes clusters from cloud providers, an operator may not know the eventual IP address for the cluster’s API until it is deployed. In this case, the operator must stop the deployment of the entire system so that they can wire this IP address through to the dependent bundles.

A better experience would allow the operator to construct a list of bundles they wish to deploy and have the runtime figure out the dependencies of each as well as link the appropriate parameters and credentials. A risk of leaving inter-bundle dependencies unspecified is that the community starts to adopt divergent solutions to this problem and never truly creates compatibility between CNAB runtimes.

WDYT?

**Comment by ryanmoran** [comment]
@jeremyrickard did I hear correctly during the call this week that you also had a proposal in this space?

**Comment by squillace** [comment]
@jeremyrickard you wanna catch @ryanmoran up with what we have here?

**Comment by technosophos** [comment]
I believe that this can be closed now that #166 is merged.
