### ISSUE TITLE
Questions on specificity of the specifcation

### ISSUE THREAD

**Issue by garethr** [deislabs/cnab-spec#66]
Before spotting #36 I wrote up a sample JSON Schema for `bundle.json`, and jotted down a few ambiguities or questions I came across. See  https://gist.github.com/garethr/5e45b35bff950ad3b62dd98fe592f3d3 for the schema.

1. is `schemaVersion` required?
2. If `schemaVersion` is not required, what is the expected behaviour?
3. The example in the spec has a `uri` field for images, but the spec doesn't mention this field?
4. For field selectors section referring to other specs (like the rough [JsonPath](https://goessner.net/articles/JsonPath/), [JSON Pointer - RFC6901](https://tools.ietf.org/html/rfc6901) and XPath) might be wise
5. Should `invocationImages` be required?
6. Should `additionalProperties` be allowed that are not defined in the spec?
7. `string, int, boolean` for `parameters.type` shortens `int` but doesn't shorten `boolean`

Happy to submit PRs to address these once we have answers.

**Comment by garethr** [comment]
A further question came up while using the schema:

8. At present `modifies` on `actions` are not required, however the default behaviour isn't specified.

**Comment by technosophos** [comment]
I noticed the schemaVersion thing while working on another PR, and made it required: https://github.com/deislabs/cnab-spec/pull/73/files

**Comment by technosophos** [comment]
For `modifies`, I think we probably should  make it `false` by default.

**Comment by technosophos** [comment]
I'll do an update an PR it

**Comment by technosophos** [comment]
Okay, a few clarifications as I work through this:

- For additional properties, I decided not to get too strict on this version of the schema. I tried to prevent the top level object from being co-opted like in `package.json`, but ignored most of the nested objects. I'm open to guidance on what we should do here.
- For `uri`, I'm not totally sure what this is for. @bacongobbler can you clarify?
- For field selectors, yeah... we need to decide on that. I think @simonferquel 's recent ideas may allow us to remove that entire part of the spec, which would be great. It's totally underbaked.
- `invocationImages` is required because without it, the thing is not a CNAB. I'll clarify that in the spec.
- The `string`, `int`, `boolean` came from ARM (which in turn came from C#, I believe). I'm not opposed to shortening `boolean` to `bool` or expanding `int` to `integer`. Which is preferable?

I'll do a PR with the ones I know the answer to. For the rest, we should keep discussing.

**Comment by bacongobbler** [comment]
>     * For `uri`, I'm not totally sure what this is for. @bacongobbler can you clarify?

According to [this commit in duffle](https://github.com/deislabs/duffle/commit/2d750ac4beca530d8aa5c8816325a1c9e799b7a8), the `uri` field was for the image's canonical name and tag. This should probably be updated to the `image` field like what's referenced [in the schema file](https://github.com/deislabs/cnab-spec/blob/e32982a866cc9dff86f89e3f25f28afdcc7539cf/schema/bundle.schema.json#L157-L160).

**Comment by technosophos** [comment]
Okay. I will try to fix that up.

**Comment by technosophos** [comment]
Okay, new fixes this time around:

- Removed `uri` in favor of `image`
- Fixed formatting on JSON files 

The following changes are deferred to other PRs:
- The changes to the `int` thing will come in #77.
- locking down more of the JSON schema when #104 gets merged

The following are deferred pending more discussion:
- field selectors, which we will hopefully get rid of with a new PR

So I'd consider this one effectively complete.
